#=================================================
# https://github.com/miaoxinwei/openwrt_build
# Description: Build OpenWrt using GitHub Actions
# Lisence: AGPL-3.0
# Author: MXW
#=================================================

name: lean编译

on:
  # watch:
  #   types: [started]
  
  push:
    branches:
      - master
    paths:
      - 'lean/buildInfo.yml'
#    schedule:
#      - cron: 0 20 * * *


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: 校验本地文件
        uses: actions/checkout@master
        with:
          ref: master

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d/* /etc/mysql /etc/php
          sudo swapoff /swapfile
          sudo rm -f /swapfile
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev python3 patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib linux-libc-dev:i386
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

      - name: 克隆代码
        env:
          REPO_URL: https://github.com/coolsnowwolf/lede
          REPO_BRANCH: master
        run: git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: 自定义配置
        env:
          CUSTOM_SH: 'custom.sh'
        run: |
          cd openwrt
          mv ../lean/$CUSTOM_SH ./ && chmod 777 $CUSTOM_SH && ./$CUSTOM_SH

      - name: 构建程序包
        run: |
          cd openwrt
          echo -e "\nsrc-git lienol https://github.com/Lienol/openwrt-package" >> feeds.conf.default
          ./scripts/feeds clean
          ./scripts/feeds update -a

          rm -rf feeds/lienol/package/openssl1.1
          rm -rf feeds/lienol/package/ipt2socks
          rm -rf feeds/lienol/package/shadowsocksr-libev
          rm -rf feeds/lienol/package/pdnsd-alt
          rm -rf feeds/lienol/package/v2ray
          rm -rf feeds/lienol/package/verysync
          rm -rf feeds/lienol/others/*

          cd feeds/lienol/lienol/
          rm -rf `ls | egrep -v '(luci-app-passwall|luci-app-v2ray-server|luci-app-trojan-server|luci-app-ipsec-vpnserver-manyusers|luci-app-pptp-vpnserver-manyusers|luci-app-fileassistant)'`
          cd ../../../

          rm -rf package/lean/kcptun
          rm -rf package/lean/trojan
          rm -rf package/lean/luci-app-pptp-server
          rm -rf package/lean/luci-app-v2ray-server

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: config文件
        run: |
          cd openwrt
          rm -f .config*
          cp ../lean/x86_64.config .config
          make defconfig

      - name: 下载编译所需源码
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: 进行固件编译
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: 清理不必要的文件
        run: |
          cd openwrt
          find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}
          find ./bin/targets/ -name "*rootfs*img*" | xargs rm -rf {}

      - name: 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./openwrt/bin/targets/
